#!/usr/bin/env python
# encoding: utf-8
#
# Nanomsgxx doc build script.
from waflib.Task import Task
import os

class ronn(Task):

    def make_ronn_command(self):
        return [
            'RONN_STYLE=' + self.env.basename,
            'ronn',
            '--organization', "'achille.roussel@gmail.com'",
            '--manual', 'nanomsgxx',
            '--style', 'dark,nnxx,highlight',
            self.inputs[0].abspath(),
        ]

    def make_mv_command(self):
        return [
            'mv',
            self.outputs[0].abspath(),
            self.outputs[0].abspath() + '.tmp',
        ]

    def make_colorsyntax_command(self):
        return [
            os.path.join(self.env.basename, 'colorsyntax'),
            '-s',
            'monokai',
            '<',
            self.outputs[0].abspath() + '.tmp',
            '>',
            self.outputs[0].abspath(),
        ]

    def make_rm_command(self):
        return [
            'rm',
            '-f',
            self.outputs[0].abspath() + '.tmp',
        ]

    def make_command(self):
        return                                         \
            self.make_ronn_command()        + ['&&'] + \
            self.make_mv_command()          + ['&&'] + \
            self.make_colorsyntax_command() + ['&&'] + \
            self.make_rm_command()

    def run(self):
        return self.exec_command(' '.join(self.make_command()))

def html_output_file(waf, input_file):
    name = input_file.name.replace('.ronn', '.html')
    path = input_file.parent.abspath()[len(waf.path.abspath()):]
    return waf.path.make_node(os.path.join(path, name))

def roff_output_file(waf, input_file):
    name = input_file.name.replace('.ronn', '')
    path = input_file.parent.abspath()[len(waf.path.abspath()):]
    return waf.path.make_node(os.path.join(path, name))

def build(waf):
    waf.env.basename = waf.path.abspath()

    css_files  = waf.path.ant_glob('**/*.css')
    idx_files  = waf.path.ant_glob('**/index.txt')
    html_files = []
    roff_files = []

    for input_file in waf.path.ant_glob('**/*.ronn'):
        html_file = html_output_file(waf, input_file)
        html_files.append(html_file)

        roff_file = roff_output_file(waf, input_file)
        roff_files.append(roff_file)

        ronn_task = ronn(env=waf.env)
        ronn_task.set_inputs([input_file] + css_files + idx_files)
        ronn_task.set_outputs([html_file, roff_file])
        waf.add_to_group(ronn_task)

    waf.install_files(waf.env.install_html_path, html_files)

def configure(waf):
    waf.find_program('cat')
    waf.find_program('ronn')
