.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NNXX::THIS_THREAD" "3" "May 2014" "achille.roussel@gmail.com" "nanomsgxx"
.
.SH "NAME"
\fBnnxx::this_thread\fR \- namespace for local thread related functions
.
.SH "SEE ALSO"
nnxx(3)
.
.br
nanomsgxx(7)
.
.SH "AUTHORS"
Achille Roussel
